---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /showback-defaulter-v1
  failurePolicy: Ignore
  name: showbackboss.shopify.io
  rules:
  - apiGroups:
    - ""
    - apps
    - batch
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
    - jobs
    - daemonsets
    - deployments
    - statefulsets
  sideEffects: None
