
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app: defaulting-controller
    control-plane: controller-manager
  type: ClusterIP
